server:
  port: 9999

spring:
  application:
    name: elasticsearch-book
  thymeleaf:
    prefix: classpath:/templates/
  # Elasticsearch客户端配置
  elasticsearch:
    host: localhost
    port: 9200
    scheme: http
    socket-timout: 30000
    connection-timeout: 1500
    read-timeout: 10000
    connection-request-timout: 500
    max-connection-num: 100
    max-connection-per-route: 100
    region: cn-northwest-1 # 当使用AWS ES时，需要配置AWS region
