spring:
  profiles:
    active: dev
  aop:
    auto: true
  application:
    name: elasticsearch-book
  thymeleaf:
    prefix: classpath:/templates/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false